# Generated by Django 5.0.6 on 2024-06-19 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_curso'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alunos',
            new_name='Aluno',
        ),
    ]
